name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Is your feature request related to a problem? What workflow is painful right now?
      placeholder: "I'm frustrated when I have to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've tried?

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - iOS App
        - Worker Backend (Node.js)
        - Docker / Deployment
        - Documentation
        - Other
